crystalcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('crystals/', views.crystals_index, name='index'),
    path('crystals/<int:crystal_id>/', views.crystals_detail, name='detail'),
    path('crystals/create/', views.CrystalCreate.as_view(), name='crystals_create'),
    path('crystals/<int:pk>/update/', views.CrystalUpdate.as_view(), name='crystals_update'),
    path('crystals/<int:pk>/delete/', views.CrystalDelete.as_view(), name='crystals_delete'),
    path('crytals/<int:crystal_id>/add_cleansing/', views.add_cleansing, name='add_cleansing'),
    path('crystals/<int:crystal_id>/assoc_location/<int:location_id>/', views.assoc_location, name='assoc_location'),
    path('crystals/<int:crystal_id>/assoc_location/<int:location_id>/remove', views.assoc_location_remove, name='assoc_location_remove'),
    path('locations/', views.LocationList.as_view(), name='locations_index'),
    path('locations/<int:pk>/', views.LocationDetail.as_view(), name='location_detail'),
    path('locations/create/', views.LocationCreate.as_view(), name='locations_create'),
    path('locations/<int:pk>/delete/', views.LocationDelete.as_view(), name='locations_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

METHODS = (
    ('S', 'Smudging'),
    ('W', 'Running Water'),
    ('M', 'Full Moon'),
    ('O', 'Other')
)


class Location(models.Model):
    place = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.place}'
    
    def get_absolute_url(self):
        return reverse('location_detail', kwargs={'pk': self.id})

class Crystal(models.Model):
    name = models.CharField(max_length=100)
    family = models.CharField(max_length=100)
    hardness = models.IntegerField()
    color = models.CharField(max_length=100)
    location = models.ManyToManyField(Location)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'crystal_id': self.id})
    
    # def cleansed_for_the_month(self):
    #     return self.cleansing_set.filter(date=date.today()).count() >= 30

class Cleansing(models.Model):
    date = models.DateField('cleansing date')
    method = models.CharField(
        max_length=1,
        choices=METHODS,
        default=METHODS[0][0]
    )
    crystal = models.ForeignKey(Crystal, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_method_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from ast import Mod
from dataclasses import field
from django.forms import ModelForm
from .models import Cleansing, Location

class CleansingForm(ModelForm):
    class Meta:
        model = Cleansing
        fields = ['date', 'method']

class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Crystal, Location
from .forms import CleansingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def crystals_index(request):
    crystals = Crystal.objects.filter(user=request.user)
    return render(request, 'crystals/index.html', {'crystals': crystals})

@login_required
def crystals_detail(request, crystal_id):
    crystal = Crystal.objects.get(id=crystal_id)
    loc_crystal_isnt = Location.objects.exclude(id__in = crystal.location.all().values_list('id'))
    cleansing_form = CleansingForm()
    return render(request, 'crystals/detail.html', {
        'crystal': crystal, 'cleansing_form': cleansing_form,
        'location': loc_crystal_isnt
    })

@login_required
def add_cleansing(request, crystal_id):
    form = CleansingForm(request.POST)
    if form.is_valid():
        new_cleansing = form.save(commit=False)
        new_cleansing.crystal_id = crystal_id
        new_cleansing.save()
    return redirect('detail', crystal_id=crystal_id)

@login_required
def assoc_location(request, crystal_id, location_id):
    Crystal.objects.get(id=crystal_id).location.add(location_id)
    return redirect('detail', crystal_id=crystal_id)

@login_required
def assoc_location_remove(request, crystal_id, location_id):
    Crystal.objects.get(id=crystal_id).location.remove(location_id)
    return redirect('detail', crystal_id=crystal_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class CrystalCreate(CreateView):
    model = Crystal
    fields = ['name', 'family', 'hardness', 'color']
    success_url = '/crystals/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CrystalUpdate(UpdateView):
    model = Crystal
    fields = ['family', 'hardness', 'color']

class CrystalDelete(DeleteView):
    model = Crystal
    success_url = '/crystals/'

class LocationList(ListView):
    model = Location
    template_name = 'locations/index.html'

class LocationDetail(DetailView):
    model = Location
    template_name = 'locations/detail.html'

class LocationCreate(CreateView):
    model = Location
    fields = '__all__'

class LocationDelete(DeleteView):
    model = Location
    success_url = '/locations/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
    <h1>About the Crystal Collector</h1>
    <hr />
    <p>Use this app to see the crystals you have, when they were last cleansed, and where they might be!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <title>Crystal Collector</title>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo">&nbsp;&nbsp;CrystalCollector</a>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'crystals_create' %}">Add a Crystal</a></li>
                    <li><a href="{% url 'index' %}">View All My Crystals</a></li>
                    <li><a href="{% url 'locations_index' %}">View All Locations</a></li>
                    <li><a href="{% url 'locations_create' %}">Add a Location</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
        <div class="right">
            All Rights Reserved, &copy; 2022 Crystal Collector &nbsp;
        </div>
    </footer>
</body>
</html>

main_app/templates/crystals/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Crystal Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ crystal.name }}</span>
                <p>Mineral Family: {{ crystal.family }}</p>
                <p>Hardness: {{ crystal.hardness }}</p>
                <p>Color: {{ crystal.color }}</p>
            </div>
            <div class="card_action">
                <a href="{% url 'crystals_update' crystal.id %}">Edit</a>
                <br />
                <a href="{% url 'crystals_delete' crystal.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_cleansing' crystal.id %}" method="post">
            {% csrf_token %} {{ cleansing_form.as_p }}
            <input type="submit" class="btn" value="Add Cleasning" />
        </form>
        <!-- {% if crystal.cleansed_for_the_month %}
        <div class="card-panel teal-text center-align">
            {{crystal.name}} has been cleansed within the past month.
        </div>
        {% else %}
        <div class="card-panel red-text center-align">
            {{crystal.name}} might need to be cleansed.
        </div>
        {% endif %} -->
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Method</th>
                </tr>
            </thead>
            <tbody>
                {% for cleansing in crystal.cleansing_set.all %}
                <tr>
                    <td>{{cleansing.date}}</td>
                    <td>{{cleansing.get_method_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr />
<div class="row">
    <div class="col s6">
        <h3>{{ crystal.name }}'s Location</h3>
        {% if crystal.location.count %} {% for location in crystal.location.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    The crystal is on/in my {{ location.place }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_location_remove' crystal.id location.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Move</button>
            </form>
            </div>
        </div>
        {% endfor %} {% else %}
        <h5>No Recorded Location</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Move Your Crystal</h3>
        {% if location.count %}
            {% for location in location.all %}
                <div class="card">
                    <div class="card-content">
                        <span>{{ location.place }}</span>
                    </div>
                    <div class="card-action">
                            <form action="{% url 'assoc_location' crystal.id location.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add</button>
                            </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>{{ crystal.name }} Has Too Many Locations And Might Get Lost!</h5>
        {% endif %}
    </div>
</div>
<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    var selectEl = document.getElementById('id_method');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/crystals/index.html
{% extends 'base.html' %} {% block content %}

<h1>Crystal List</h1>

{% for crystal in crystals %}
<div class="card">
    <div class="card-content">
        <span class="card-title">{{ crystal.name }}</span>
        <p>Name: {{ crystal.name }}</p>
        <p>Mineral Family: {{ crystal.family }}</p>
        <p>Hardness: {{ crystal.hardness }}</p>
        <p>Color: {{ crystal.color }}</p>
        
    </div>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Welcome to Crystal Collector</h1>
<hr />
{% endblock %}

main_app/templates/locations/detail.html
{% extends 'base.html' %} {% block content%}
<h1>Location Details</h1>

<div class="card">
    <a href="{% url 'location_detail' location.id %}">
        <div class="card-content">
            <span class="card-title">{{ location.place }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'location_delete' location.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/locations/index.html
{% extends 'base.html' %} {% block content %} {% for location in location_list %}
<div class='card'>
    <a href="{% url 'location_detail' location.id %}">
        <div class="card-content">
            <span>{{ location.place }}</span>
        </div>
    </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/main_app/crystal_confirm_delete.html
{% extends 'base.html' %} {% block content%}
<h1>Remove Crystal</h1>

<h4>
    Are you sure you want to remove
    <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Remove" class="btn" />
    <a href="{% url 'detail' crystal.id %}">Cancel</a>
</form>
{% endblock%}

main_app/templates/main_app/crystal_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Crystal</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/location_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Toy</h1>

<h4>
    Are you sure you want to delete
    <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete" />
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/location_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Update {{ object.name }}</h1>
{% else %}
<h1>Add Location</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input
        class="btn blue"
        type="submit"
        value="{% if object %} Update Location {% else %} Add Location {% endif %}"
    />
</form>

{% endblock %}